apiVersion: v1
kind: ConfigMap
metadata:
  name: moviehub-config
  namespace: moviehub
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  JWT_ISSUER: "MovieHub.AuthService"
  JWT_AUDIENCE: "MovieHub.Client"
  GOOGLE_CLOUD_PROJECT: "moviehub-production"
